Use Proptypes own library
cRicateau/react-loopback-generator pull request #2
Opened 2017-09-27 08:48 UTC by niwox

2017-09-29 13:23 UTC, souvir approved these changes

2017-10-02 20:06 UTC, cRicateau requested changes

2017-10-02 20:06 UTC, cRicateau commented on generators/client-component/templates/component.jsx
> +import React, {Component } from 'react';
{ Component }

2017-10-02 20:06 UTC, cRicateau commented on generators/client-component/templates/view.jsx
> +import React, {Component } from 'react';
idem

2017-10-05 10:01 UTC, closed without merging